osdpctl/include/arg_parser.h
src/osdp_common.c

I ran into there issues while running the controller on a raspberry pi and the PD code on a smaller MCU which does not support unaligned accesses.

Portability changes.

---

python/pyosdp_cp.c

- Fix memory leak of return object None.
- Fix incorrect error check from hstrtoa.
Signed-off-by: Johan Carlsson <johan.carlsson@teenage.engineering>

Fix python memory leak and python keyset error check.

---

src/osdp_cp.c

Adding restriction so that you cannot queue commands then the pd is not online.
Without this it will start to send command before the security challenge is done.
Signed-off-by: Johan Carlsson <johan.carlsson@teenage.engineering>

Add checks that a pd is online before queueing commands.

---

src/osdp_pd.c

without this change pd will hang if it receives too many bytes.
it might also hang if the LEN_LSB or LEN_MSB is corrupted.
Signed-off-by: Johan Carlsson <johan.carlsson@teenage.engineering>

PD: always check the timeout on receiving packets

---

python/pyosdp_utils.c

This solves the crash i've been seeing. What seems to happen
is that PyArg_Parse writes to a 64-bit type and we input a
32-bit, so the buf pointer have its lowest 4 bytes corrupted.
Signed-off-by: Johan Carlsson <johan.carlsson@teenage.engineering>

python: change len from int to the correct type of Py_ssize_t.

---

src/osdp_cp.c
src/osdp_pd.c

when skipping commands addressed to other nodes the rx queue
should not be flushed. The complete command is already received and
flushing the rx queue only risks removing bytes in the next command.

do not flush rx queue when skipping commands.

---

src/osdp_cp.c
src/osdp_pd.c

While doing some fuzzing I ran into an interesting issue. I run two PD on the same wires and introduced some bad data on the wires.
When doing so I was able to get the serial device out of sync with the channel lock. What happens is that CP sends a command and immediately it receives some invalid data. This triggers error cleanup which flushes the RX queue. However this flush happens before it gets its reply so in the RX queue there now is a complete reply to the command.
Next the channel lock will be released and the next command will receive the reply from the other PD because the reply was was already in the RX queue. The CP never recovers from this since will be continue and send a command to PD A and B and receive the wrong reply every time.
I solve this issue by always flushing the …

Avoid receiving invalid data by flushing rx before each send.

---

src/osdp_phy.c

The checksum field in the packet was being read at the offset of len-1
instead of pkt_len-1.

Fix the check of the checksum of received packets.

---

src/osdp_cp.c

`pd->rx_buf_len` is 0 both when `pd->channel.send()` is called and here at the call to `osdp_dump()`

Call to osdp_dump was using incorrect length

---

src/osdp_pd.c

Do not check or send the first entry in the pd->cp[] device capability
table which is for function code 0 which is not a defined function code.

pd: Fix device capabilities report

---

src/osdp_common.h
src/osdp_config.h.in
src/osdp_cp.c
src/osdp_phy.c
src/osdp_sc.c

This proposed change is to add detection and handling by the CP of a busy reply from a PD where the busy reply was sent with sequence number 0, as per the OSDP specification.  Otherwise the busy reply would be rejected as having a "packet seq mismatch".
Also, the building of the osdp_CHLNG(0x76) command is modified to not perform the generation of random numbers each time the message is sent (or re-sent).  Instead the random number generation is moved to osdp_sc_init().  Otherwise new random numbers could cause the challenge response to be rejected due to the PD possibly using the random numbers from a previously sent osdp_CHLNG command when it replied busy.
Previously the following timeout was used for both retrying commands and retrying to establish communications: 
```
#define …
```

cp: Improved busy reply handling

---

src/osdp_common.h
src/osdp_pd.c

Also fix the description comment for OSDP_PD_NAK_SEQ_NUM.

pd: Use better NAK error code when rejecting a command due to SC inactive

---

src/osdp_cp.c

Change the check related to the master key so that the master key is
used and accessed if and only if it is not NULL.  Previously a NULL or
undefined master key could be used if the count of individually set
SCBKs was less than the number of PD.

Fix the master key check in osdp_cp_setup()

---

src/osdp_cp.c

This particular device would not respond to `CMD_ID` without first issuing `CMD_POLL`
Adding `CMD_POLL` to `OSDP_CP_STATE_INIT` fixed this.
The device also replies to `CMD_POLL` with `REPLY_ISTATR` on occasion which dropped the connection. Ignoring this reply and logging a warning fixes this.
Also fixed incorrect logging of `CMD_CAP` where it should have been `CMD_ID`

Small changes found when testing with Inner Range SIFER reader

---

include/osdp.h
include/osdp.hpp
src/osdp_common.c
src/osdp_common.h
src/osdp_cp.c
src/osdp_pd.c

Added opaque pointer argument to command complete callback, so at this way we can pass a context or instance class to be able to access to class members. This is similar to command or event callbacks behavior, we pass the void *arg to the callbacks.

libosdp: Added opaque argument to command_complete_callback

---

src/osdp_pd.c

It looks like support for `REPLY_ISTATR` and `REPLY_OSTATR` already exists. This just removes the code that is preventing them from being used.

Enable REPLY_ISTATR and REPLY_OSTATR support

---

src/osdp_pd.c

When receiving a non-multicast packet addressed to another PD, the PD kept trying to process it indefinitely instead of moving on to the next packet in the RX ring buffer.

PD: Reset phy state when ignoring a packet

---

cmake/LibOSDPConfig.cmake.in
osdpctl/CMakeLists.txt
python/setup.py.in
samples/c/CMakeLists.txt
samples/cpp/CMakeLists.txt
src/CMakeLists.txt
tests/unit-tests/CMakeLists.txt

Fix for #107 
When using libosdp, you can now link in cmake with:
```
find_package(LibOSDP)
target_link_libraries( target-name PRIVATE libosdp::osdp)
```

Fix cmake package file

---

doc/libosdp/secure-channel.rst

Fix two typos found in the secure channel documentation.

Fix typos in secure channel docs

---

src/osdp_pd.c

According OSDP v2.2, output control, buzzer & LED message packet may contain multiple records. Currently, the lib support this only for output control command. This PR add this feature for buzzer & LED command.

fix LED & Buzzer repeated command

---

python/pyosdp_cp.c

While deploying my application to a 32bit ARM device, I found the bitmask logic broke when using the python bindings.
After investigation I saw the usage of `uint64_t`. 
After converting to `uint32_t`, the bitmask logic now works across both 32bit and 64bit architectures.

Python Bindings: 32bit ARM capability w/ bitmask

---

doc/protocol/introduction.rst
include/osdp.h
osdpctl/cmd_send.c
osdpctl/config.c
src/osdp_pd.c

According specification, half-duplex asynchronous serial should support at least one of 9600, 19200, 38400, 57600, 115200, 230400 Baud. Adding support for 57600.

Add support for additional baud rate 57600

---

include/osdp.hpp

Fixes #129.
Adds a check to the destructors of **OSDP::ControlPanel** and **OSDP::Peripheral** to see if the context has been set during the object's lifetime. This decides whether a teardown should happen or not. An uninitialized object would otherwise fail when being destroyed.

C++ wrapper, only call teardown in destructors if context exists

---

include/osdp.hpp

Add header guards to osdp.hpp to prevent multiple inclusions of the same header file. osdp.h already has this.

c++: add header guards

---

python/pyosdp_pd.c
python/setup.py.in
src/osdp_common.c
tests/pytest/README.md
tests/pytest/test_status.py
tests/pytest/testlib/control_panel.py
tests/pytest/testlib/peripheral_device.py

Also add tests for the added PD status.

Add support for PD online status

---

rust/Cargo.toml
rust/build.rs
rust/src/channel/mod.rs
rust/src/commands.rs
rust/src/cp.rs
rust/src/events.rs
rust/src/lib.rs
rust/src/pd.rs

The Rust crate currently depends heavily on `std`. Since OSDP is a protocol mostly for embedded devices I think `no_std` support is necessary.
This PR adds that support by:
- Using `core::*` and `alloc::*` types instead of `std::*` where possible.
- Defining a feature `"std"`, which users can opt out of. Things like `UnixChannel` or the `file` API will not be available then.
- Using [`parking_log`](https://crates.io/crates/parking_lot) and [`spin`](https://crates.io/crates/spin) as a replacement for `std::sync::Mutex`. I chose `parking_lot`, because it is widely used, cross platform and supports [`lock_api`](https://crates.io/crates/lock_api) and can therefore be used just like `spin::Mutex` for `no_std` without any changes. The use of `spin` should be temporary, because this is almost …

rust: no_std support

---

rust/Cargo.toml
rust/src/channel/mod.rs

Some of the dependencies weren't used and `lazy_static` could be replaced by `once_cell` which was used anyway.

rust: Reduced number of dependencies

---

include/osdp.h

This is necessary because we are dealing with a Manufacturer Specific Response that contains at least 73 bytes of date.  The data is an ASN.1 serialized ECDSA P256 signature.  In the case of larger curves (e.g. P384) the signature will be longer but 128 bytes will handle it fine.  In the case of RSA signatures it is almost for sure that 128bytes will be too small but that is not a use case we are concerned with at the moment nor is it one we can test.

Increasing the max data contained in an OSDP event to 128bytes

---

src/osdp_cp.c

Repaired references to the function that returns the current milliseconds. In several instances, it mistakenly referred to the utils dependency millis_now() instead of osdp_millis_now(). This became problematic when overriding osdp_millis_now with embedded platform-specific functions.

Repaired references to osdp_millis_now()

---

misc/osdp_dissector.lua

This fixes a couple of very minor typos in protocol field names and info metadata in the Wireshark OSDP dissector.

Fix minor typos in the Wireshark payload dissector

---

src/osdp_pd.c

Seems like this is just a typo to me, unless I do not understand. Not sure why we would want to "fail to decode" when the command callback returns successfully.
Was noticing this:
```
reading: ffffffff5300080006676ebc (this log is from SerialChannel)
OSDP: PD-0: [2024-04-12T22:55:12Z] [WARN ] vendor/src/osdp_phy.c:521: Packet scan skipped 3 bytes before SoM
command received (from command callback)
OSDP: PD-0: [2024-04-12T22:55:12Z] [ERROR] vendor/src/osdp_pd.c:661: Failed to decode command: CMD(67) Len:0 ret:-2
OSDP: PD-0: [2024-04-12T22:55:12Z] [DEBUG] vendor/src/osdp_pd.c:669: CMD: RSTAT(67) REPLY: NAK(41)
writing: ff5380090006410224fa (this log is from SerialChannel)
```
when using a basic command callback like this (in Python):
```
def handle_command(self, command):
print('command …
```

Continue normally on successful command callback on status commands

---

src/osdp_cp.c

Small fix. developer probably forgot to change this line after a copy/paste.

fix offline notification

---

examples/platformio/cp.ino

Functions were swapped, making the example fail with `[ERROR] Channel send for 10 bytes failed! ret: 0`.

Fix PlatformIO CP example

---

include/osdp.h
python/osdp_sys/data.c
src/osdp_cp.c
src/osdp_pd.c
tests/pytest/test_commands.py
tests/pytest/test_events.py
tests/unit-tests/test-commands.c
tests/unit-tests/test-events.c

This PR fix the command MFG : the "command" field disapeared in OSDP 2.2 specification (only tested on PD devices).

MFG: remove command field on OSDP 2.2
